# -*- coding: utf-8 -*-
"""ScannerManager.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12u9dHeW_bXLaYEbRGuWbt4aOnt1z3BpS
"""

import ResultPrinter

class ScannerManager:
  def __init__(self):
    
  def execute(self, lung_detection_model, result_printer, lung_detection_result_table, ct_image_table):
    patient_number = len(lung_detection_result_table)

    for i in range(patient_number):
      lung_detection_result_table.make_new_list()

      for j in range(len(lung_detection_result_table[i])):
        image_scan_result = lung_detection_model.predict(lung_detection_result_table[i][j])
        lung_detection_result_table.add_result(image_scan_result)

    return ResultPrinter(lung_detection_result_table, ct_image_table).make_result()